export const AuditAction = {
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_ACTIVATED: 'USER_ACTIVATED',
  USER_PASSWORD_RESET: 'USER_PASSWORD_RESET',
  PACKAGE_CREATED: 'PACKAGE_CREATED',
  PACKAGE_UPDATED: 'PACKAGE_UPDATED',
  PACKAGE_PRICE_CHANGED: 'PACKAGE_PRICE_CHANGED',
  PACKAGE_STATUS_CHANGED: 'PACKAGE_STATUS_CHANGED',
  PACKAGE_DELETED: 'PACKAGE_DELETED',
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_PRICE_CHANGED: 'PRODUCT_PRICE_CHANGED',
  PRODUCT_STATUS_CHANGED: 'PRODUCT_STATUS_CHANGED',
  PRODUCT_DELETED: 'PRODUCT_DELETED',
  BILL_CANCELLED: 'BILL_CANCELLED',
  BILL_REFUNDED: 'BILL_REFUNDED',
  BILL_DISCOUNT_ABOVE_THRESHOLD: 'BILL_DISCOUNT_ABOVE_THRESHOLD',
  BILL_PAYMENT_RECORDED_BY_OTHER: 'BILL_PAYMENT_RECORDED_BY_OTHER',
  BILL_MARKED_AS_TEST: 'BILL_MARKED_AS_TEST',
  BILL_UNMARKED_AS_TEST: 'BILL_UNMARKED_AS_TEST',
  BILL_GROUP_RATE_ENTERED: 'BILL_GROUP_RATE_ENTERED',
  SESSION_VOIDED: 'SESSION_VOIDED',
  SESSION_FORCE_CLOSED: 'SESSION_FORCE_CLOSED',
  SESSION_EXTRA_REMOVED: 'SESSION_EXTRA_REMOVED',
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
  CUSTOMERS_MERGED: 'CUSTOMERS_MERGED',
  REPORT_EXPORTED: 'REPORT_EXPORTED',
} as const;

export type AuditAction = (typeof AuditAction)[keyof typeof AuditAction];

export const AuditEntityType = {
  USER: 'USER',
  PLAY_PACKAGE: 'PLAY_PACKAGE',
  BILL: 'BILL',
  SETTINGS: 'SETTINGS',
  CUSTOMER: 'CUSTOMER',
  PLAY_SESSION: 'PLAY_SESSION',
  PRODUCT: 'PRODUCT',
  REPORT: 'REPORT',
} as const;

export type AuditEntityType = (typeof AuditEntityType)[keyof typeof AuditEntityType];
