export const AuditAction = {
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_ACTIVATED: 'USER_ACTIVATED',
  USER_PASSWORD_RESET: 'USER_PASSWORD_RESET',
  PACKAGE_CREATED: 'PACKAGE_CREATED',
  PACKAGE_UPDATED: 'PACKAGE_UPDATED',
  PACKAGE_PRICE_CHANGED: 'PACKAGE_PRICE_CHANGED',
  PACKAGE_STATUS_CHANGED: 'PACKAGE_STATUS_CHANGED',
  PACKAGE_DELETED: 'PACKAGE_DELETED',
  BILL_CANCELLED: 'BILL_CANCELLED',
  BILL_REFUNDED: 'BILL_REFUNDED',
  BILL_DISCOUNT_ABOVE_THRESHOLD: 'BILL_DISCOUNT_ABOVE_THRESHOLD',
  SESSION_VOIDED: 'SESSION_VOIDED',
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
} as const;

export type AuditAction = (typeof AuditAction)[keyof typeof AuditAction];

export const AuditEntityType = {
  USER: 'USER',
  PLAY_PACKAGE: 'PLAY_PACKAGE',
  BILL: 'BILL',
  SETTINGS: 'SETTINGS',
  CUSTOMER: 'CUSTOMER',
  PLAY_SESSION: 'PLAY_SESSION',
} as const;

export type AuditEntityType = (typeof AuditEntityType)[keyof typeof AuditEntityType];
